[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "ARvEkVp3yEwfAyLxRrEqCULMgNJBHNGjwSdEqSwDgCQ5"

[programs.devnet]
counter = "ARvEkVp3yEwfAyLxRrEqCULMgNJBHNGjwSdEqSwDgCQ5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./SrunNkgXdSWerx9e51pVgFCtKJ3EoCskEkSoTquXHX7.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
